site_name: B-Zone Roleplay Wiki
repo_url: https://github.com/robertnitu02/test-wiki
repo_name: robertnitu02/test-wiki
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: robertnitu02/test-wiki
      branch: master
  - git-authors

copyright: |
  &copy; 2023 <a href="https://v.b-zone.ro/"  target="_blank" rel="noopener">B-Zone Roleplay</a>